name: test

on: [push]

jobs:
  test-win:
    name: Test on Windows
    runs-on: windows-latest

    steps:
      - name: Check out files
        uses: actions/checkout@main

      - name: Setup gsc-tool
        uses: diamante0018/setup-gsc-tool@main
        with:
          version: "1.2.0"

      - name: Compile test script
        run: |
          gsc-tool.exe comp t6 pc .

  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Check out files
        uses: actions/checkout@main

      - name: Setup gsc-tool
        uses: diamante0018/setup-gsc-tool@main
        with:
          version: "1.2.0"

      - name: Compile test script
        run: |
          ./gsc-tool comp t6 pc .

  test-macos:
    name: Test on macOS
    runs-on: macos-latest

    steps:
      - name: Check out files
        uses: actions/checkout@main

      - name: Setup gsc-tool
        uses: diamante0018/setup-gsc-tool@main
        with:
          version: "1.2.0"

      - name: Compile test script
        run: |
          ./gsc-tool comp t6 pc .
